apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  PORT: '3001'
  DB_URI: mongodb://mongo:27017/todo
  JWT_SECRET: a,b!rc~')bPz2xLtD#_~
  JWT_SECRET_REFRESH: g,b!reg~')bPz34xLt%^&U^
  CLIENT_URI: http://todo-labproj09.apps.ocp.lab.cloudpak.site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj09/serwer:1.0
        name: server
        ports:
        - containerPort: 3001
        resources: {}
        env:
        # - name: ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: password
        # - name: ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: username
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: PORT
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: DB_URI
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: JWT_SECRET
        - name: JWT_SECRET_REFRESH
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: JWT_SECRET_REFRESH
        - name: CLIENT_URI
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: CLIENT_URI
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: server
  type: ClusterIP